spring:
  main.web-application-type: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    bindings.input:
      destination: payment-notification-topic
      group: persistence-service-consumer