server:
  port: 8181

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    bindings.output:
      destination: payment-approval-topic
      contentType: application/json
