server:
  port: 8181

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    bindings.output:
      destination: payment-approval-topic
      contentType: application/*+avro
    schema:
      avro:
        schema-locations: classpath:avro/schema.avsc
    schema-registry-client:
      endpoint: http://localhost:8080

management:
  health.binders.enabled: true